[package]
name = "aetherlink-daemonctl"
version = "1.0.0"
edition = "2024"

[dependencies]
aetherlink-proto.workspace = true
anyhow.workspace = true
clap.workspace = true
prost.workspace = true
tokio.workspace = true
