[package]
name = "aetherlink-network"
version = "1.0.0"
edition = "2024"

[dependencies]
aetherlink-core.workspace = true
aetherlink-proto.workspace = true
serde.workspace = true
thiserror.workspace = true
