[package]
name = "aetherlink-core"
version = "0.4.0"
edition = "2024"

[dependencies]
aetherlink-proto.workspace = true
libp2p.workspace = true
prost.workspace = true
serde.workspace = true
thiserror.workspace = true
